config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # root to: "home#index"
  root to: "articles#index"
  resources :articles, only: [:index, :show]
  get 'search', to: 'search#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

    def self.ransackable_attributes(auth_object = nil)
        ["body", "created_at", "id", "title", "updated_at"]
    end

    def self.ransackable_associations(auth_object = nil)
        []
    end
        
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    # before_action :authenticate_user!
    def before_action
      @posts = Article.all
      @articles = Article.all
    end
    def index
        #  @articles = Article.all 
        @q = Article.ransack(params[:q])
        @articles = @q.result
        @posts = Article.all
    end

    def show 
        @article = Article.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'redcarpet'
  require 'rouge'
  require 'rouge/plugins/redcarpet'

  class HTML < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end

  def markdown(text)
    return '' if text.nil?

    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
      prettify: true
    }

    extensions = {
      autolink: true,
      tables: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      no_intra_emphasis: true,
      strikethrough: true,
      superscript: true,
      disable_indented_code_blocks: true,
    }

    # Redcarpet::Markdown.new(HTML.new(options), extensions).render(text).html_safe
    # these 3 lines do same as above 1 line
    renderer = HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="container">
  <%= search_form_for  @q  do |f| %>
    <div id="search" class="form-group">
        <%= f.search_field :title_or_body_cont_any %>  
        <%= f.submit 'Search', class: "btn btn-outline-secondary" %>
    </div>   
  <% end %>
  <br/>

 <div class="row">
    <div class="col-9">
        <% @articles.each do |article|%>
        
          <div class="row"> 
            <div class="col-12">
              <div  class="border border-success p-2 border-opacity-25 rounded">
                <p>
                    <%= link_to article.title, article_path(article), style: 'color:#d63e2d; font-size: 40px; ' %> 
                </p>

                <p>
                    <%= markdown article.body%>
                </p>
                <br/>
                <p class="created_at">
                    <%= article.created_at.to_time.strftime(' %e %B  %Y') %>
                </p>

              </div>
            </div>
          </div>
          <br/>
       
        <%end%>
    </div>  
        <div class="col-3">
          <div class="row">
           <div  class="border border-success p-2 border-opacity-25 rounded">
             <% @posts.take(10).reverse_each do |article|%>
                <p> 
                  <%= link_to article.title, article_path(article), style: 'color:#000000;' %>
               </p>
             <% end %>
           </div>
          </div> 
          <br/>
          <div class="row">
            <div  class="border border-success p-2 border-opacity-25 rounded">
               <% @posts.take(10).each do |article|%>
             <p>  <%= link_to article.created_at.to_time.strftime(' %e %B  %Y'), article_path(article), style: 'color:#000000;' %></p>
               <% end %> 
            </div>
          </div>
        </div>
    
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <p style="color:#d63e2d; font-size: 30px;"><%= @article.title %></p>
      
      <div class="border border-success p-2 border-opacity-25 rounded">
        <p><%= markdown @article.body%></p>
      </div>
    </div>  
   </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

     <%= stylesheet_link_tag "rouge", "data-turbo-track": "reload" %>
   
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <div class="page-wrap">

      <div class="container">


        <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #FFFFFF;">
          <%= image_tag "rails_image.png"%>

          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <b><a class="nav-link" style="color: #d63e2d"  href="https://ruby-doc.org">Ruby-doc</a></b>
              <b><a class="nav-link" style="color: #d63e2d" href="https://guides.rubyonrails.org">Rubyonrails.org</a></b>
              <b><a class="nav-link" style="color: #d63e2d" href="https://stackoverflow.com/questions/tagged/ruby-on-rails">Ask for help</a></b>
              <b><a class="nav-link" style="color: #d63e2d"  href="https://github.com/vladimirlozitskiy23">Github</a></b>
            </div>
          </div>

        </nav>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>

      </div>

    </div>

    <footer class="site-footer">
      <div class="container">
        Rails blog 2023
      </div>  
    </footer>

  </body>

</html>